//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBuilder.JS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBuilder.JS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; class[headerComment] &gt;&gt;
        ///&lt;&lt; class[import] &gt;&gt;
        ///
        ///&lt;&lt; class[comment] &gt;&gt;
        ///class &lt;&lt; class[name] &gt;&gt;&lt;&lt; class[extends] &gt;&gt; {
        ///    &lt;&lt; class[constructorComment] &gt;&gt;
        ///    constructor(&lt;&lt; class[constructorParameters] &gt;&gt;) {
        ///&lt;&lt; class[property] &gt;&gt;
        ///    }
        ///    &lt;&lt; class[httpHeaderFunctionComment] &gt;&gt;
        ///    setHttpHeaders(headerObject){
        ///        for (var key in headerObject){
        ///            globalTokens[key] = headerObject[key];
        ///        }
        ///    }
        ///&lt;&lt; class[method] &gt;&gt;
        ///}
        ///
        ///&lt;&lt; class[exports] &gt;&gt;.
        /// </summary>
        internal static string _class {
            get {
                return ResourceManager.GetString("_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; class[headerComment] &gt;&gt;
        ///&lt;&lt; class[import] &gt;&gt;
        ///
        ///&lt;&lt; class[comment] &gt;&gt;
        ///class &lt;&lt; class[name] &gt;&gt;&lt;&lt; class[extends] &gt;&gt; {
        ///    &lt;&lt; class[constructorComment] &gt;&gt;
        ///    constructor(&lt;&lt; class[constructorParameters] &gt;&gt;) {
        ///&lt;&lt; class[property] &gt;&gt;
        ///    }
        ///&lt;&lt; class[method] &gt;&gt;
        ///}
        ///
        ///&lt;&lt; class[exports] &gt;&gt;.
        /// </summary>
        internal static string classPOKO {
            get {
                return ResourceManager.GetString("classPOKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export {&lt;&lt; exports[types] &gt;&gt;};.
        /// </summary>
        internal static string exports {
            get {
                return ResourceManager.GetString("exports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; function[headerComment] &gt;&gt;
        ///
        ///&lt;&lt; function[constructorComment] &gt;&gt;
        ///function &lt;&lt; function[name] &gt;&gt; (&lt;&lt; function[constructorParameters] &gt;&gt;){
        ///&lt;&lt; function[property] &gt;&gt;
        ///    &lt;&lt; function[httpHeaderFunctionComment] &gt;&gt;
        ///    this.setHttpHeaders = function(headerObject) {
        ///        for (var key in headerObject) {
        ///            globalTokens[key] = headerObject[key];
        ///        }
        ///    }
        ///&lt;&lt; function[method] &gt;&gt;
        ///}
        ///
        ///
        ///.
        /// </summary>
        internal static string function {
            get {
                return ResourceManager.GetString("function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; function[headerComment] &gt;&gt;
        ///
        ///&lt;&lt; function[constructorComment] &gt;&gt;
        ///function &lt;&lt; function[name] &gt;&gt; (&lt;&lt; function[constructorParameters] &gt;&gt;){
        ///&lt;&lt; function[property] &gt;&gt;
        ///}
        ///
        ///&lt;&lt; function[method] &gt;&gt;
        ///.
        /// </summary>
        internal static string functionPOKO {
            get {
                return ResourceManager.GetString("functionPOKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import {&lt;&lt; import[types] &gt;&gt;} from &quot;&lt;&lt; import[url] &gt;&gt;&quot;;.
        /// </summary>
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         &lt;&lt; property[comment] &gt;&gt;
        ///        this.&lt;&lt; property[name] &gt;&gt; = &lt;&lt; property[assignable] &gt;&gt;;.
        /// </summary>
        internal static string property {
            get {
                return ResourceManager.GetString("property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var globalTokens = {};
        ///
        ///class request {
        ///    constructor(baseURL, url, method, requestBindings, resultType) {
        ///        if (!baseURL.endsWith(&quot;/&quot;)) {
        ///            baseURL = baseURL + &quot;/&quot;;
        ///        }
        ///        this.BaseURL = baseURL;
        ///        this.URL = this.BaseURL + url;
        ///        this.Method = method;
        ///        this.RequestBindings = requestBindings;
        ///        this.ResultType = resultType;
        ///    }
        ///
        ///    async ExecuteRequest(parms) {
        ///        var that = this;
        ///        var requestBody = {};
        ///        var reques [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string request {
            get {
                return ResourceManager.GetString("request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var globalTokens = {};
        ////**
        /// * A very simple and lightweight cross browser polyfill for a JS promise.
        /// * Author : Philip Schoeman
        /// * @param {Function} func
        /// */
        ///var corePromise = function (func) {
        ///    var promiseScope = this;
        ///    this.funcToRun = null;
        ///    this.funcCatch = null;
        ///    this.then = function (funcThen, funcCatch) {
        ///        promiseScope.funcToRun = funcThen;
        ///        if (funcCatch) {
        ///            promiseScope.funcCatch = funcCatch;
        ///        }
        ///    };
        ///    this.catch = function (funcCatch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string requestES5 {
            get {
                return ResourceManager.GetString("requestES5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;&lt; method[comment] &gt;&gt;
        ///    async &lt;&lt; method[name] &gt;&gt; (&lt;&lt; method[parameters] &gt;&gt;){
        ///        return this._&lt;&lt; method[name] &gt;&gt;.ExecuteRequest({&lt;&lt; method[requestObj] &gt;&gt;}, globalTokens);
        ///    }
        ///.
        /// </summary>
        internal static string runRequestMethod {
            get {
                return ResourceManager.GetString("runRequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;&lt; method[comment] &gt;&gt;
        ///    this.&lt;&lt; method[name] &gt;&gt; = function(&lt;&lt; method[parameters] &gt;&gt;){
        ///        return this._&lt;&lt; method[name] &gt;&gt;.ExecuteRequest({&lt;&lt; method[requestObj] &gt;&gt;}, globalTokens);
        ///    };
        ///.
        /// </summary>
        internal static string runRequestMethodFunction {
            get {
                return ResourceManager.GetString("runRequestMethodFunction", resourceCulture);
            }
        }
    }
}
